---
- hosts: master
  become: yes
  tasks:
    - name: Run pre upgrade tasks
      include_role:
        name: upgrade
        tasks_from: pre

    - name: Run main upgrade tasks
      include_role:
        name: upgrade
        tasks_from: main

    - name: Run post upgrade tasks
      include_role:
        name: upgrade
        tasks_from: post

- hosts: node
  serial: 2
  become: yes
  tasks:
    - name: Run pre upgrade tasks
      include_role:
        name: upgrade
        tasks_from: pre

    - name: Run main upgrade tasks
      include_role:
        name: upgrade
        tasks_from: main

    - name: Run post upgrade tasks
      include_role:
        name: upgrade
        tasks_from: post
