---
- name: Test for Raspbian
  set_fact:
    raspbian: '{% if
      ( ansible_facts.architecture is search("arm") and
        ansible_facts.lsb.description is match("[Rr]aspbian.*[Bb]uster") ) or
      ( ansible_facts.architecture is search("aarch64") and
        ansible_facts.lsb.description is match("Debian.*buster") ) %}true{% else %}false{% endif %}'

- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  when:
    - raspbian is true

- name: Flush iptables before changing to iptables-legacy
  iptables:
    flush: true
  when:
    - raspbian is true

- name: Changing to iptables-legacy
  alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables
  register: ip4_legacy
  when:
    - raspbian is true

- name: Changing to ip6tables-legacy
  alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables
  register: ip6_legacy
  when:
    - raspbian is true

- name: Check swap enabled
  shell: swapon -s | wc -l
  register: swap_enabled

- name: Disable swap
  shell: "{{ item }}"
  with_items:
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile remove
    - systemctl disable dphys-swapfile.service
  when: swap_enabled.stdout != "0"

- name: apt-get update
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes
    cache_valid_time: 86400
    upgrade: full

- name: Check python-apt installed
  shell: apt -qq list python-apt
  register: python_apt_installed

- name: python-apt dependency
  shell: apt-get install -y python-apt
  args:
    warn: no
  when: python_apt_installed.stdout is search('installed')

- name: apt-get install packages
  apt:
    name: vim
    state: latest
    name: open-iscsi
    state: latest

- name: Rebooting
  reboot:
  when:
    - raspbian is true
