---
k3s_version: v1.18.4+k3s1
ansible_user: pi
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--tls-san {{ ansible_default_ipv4.address }} --flannel-backend host-gw --no-deploy servicelb"
